title: The GitHub Blog Test
author: Technicianologist
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is part of a tutorial and will be part of my portfolio.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  technicianologist # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
